# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - echo "Command not found"
    silent: true

  clean:all:
    cmds:
      - podman system prune -af

  build:all:
    deps: [clean:all]
    cmds:
      - task: build_base_img
      - task: build_dotnet8_sdk
      - task: build_aspnet8_runtime
      - task: build_dotnet8_runtime
      - task: build_golang
      - task: build_jdk_11
      - task: build_jre_11
      - task: build_python3

  build_base_img:
    dir: _base
    env:
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: devops-altlinux
    cmds:
      - podman buildx build --build-arg VER=$image_version -f Dockerfile -t $repo_url/$image_name:p10-$image_version
      - podman push $repo_url/$image_name:p10-$image_version

  build_dotnet8_sdk:
    dir: dotnet-sdk
    env:
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: altlinux-p10-dotnet-sdk
      dotnet_version: "8.0"
    cmds:
      - podman buildx build --build-arg REPO_URL=$repo_url --build-arg DOTNET_CORE_VERSION=$dotnet_version --build-arg VER=$image_version -f Dockerfile -t $repo_url/$image_name:$dotnet_version-$image_version
      - podman push $repo_url/$image_name:$dotnet_version-$image_version

  build_aspnet8_runtime:
    dir: aspnet-runtime
    env:
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: altlinux-p10-aspnet-runtime
      dotnet_version: "8.0"
    cmds:
      - podman buildx build --build-arg REPO_URL=$repo_url --build-arg DOTNET_VERSION=$dotnet_version --build-arg VER=$image_version -f Dockerfile -t $repo_url/$image_name:$dotnet_version-$image_version
      - podman push $repo_url/$image_name:$dotnet_version-$image_version

  build_dotnet8_runtime:
    dir: dotnet-runtime
    env:
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: altlinux-p10-dotnet-runtime
      dotnet_version: "8.0"
    cmds:
      - podman buildx build --build-arg REPO_URL=$repo_url --build-arg DOTNET_VERSION=$dotnet_version --build-arg VER=$image_version -f Dockerfile -t $repo_url/$image_name:$dotnet_version-$image_version
      - podman push $repo_url/$image_name:$dotnet_version-$image_version

  build_golang:
    dir: golang
    env:
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: altlinux-p10-golang
    cmds:
      - podman buildx build --build-arg VER=$image_version --build-arg REPO_URL=$repo_url -f Dockerfile -t $repo_url/$image_name:$image_version
      - podman push $repo_url/$image_name:$image_version

  build_jdk_11:
    dir: java
    env:
      java_version: 11
      java_type: jdk
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: altlinux-p10
    cmds:
      - podman buildx build --build-arg JAVA_VERSION=$java_version --build-arg JAVA_TYPE=$java_type --build-arg VER=$image_version --build-arg REPO_URL=$repo_url -f Dockerfile -t $repo_url/$image_name-$java_type:$java_version-$image_version
      - podman push $repo_url/$image_name-$java_type:$java_version-$image_version

  build_jre_11:
    dir: java
    env:
      java_version: 11
      java_type: jre
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: altlinux-p10
    cmds:
      - podman buildx build --build-arg JAVA_VERSION=$java_version --build-arg JAVA_TYPE=$java_type --build-arg VER=$image_version --build-arg REPO_URL=$repo_url -f Dockerfile -t $repo_url/$image_name-$java_type:$java_version-$image_version
      - podman push $repo_url/$image_name-$java_type:$java_version-$image_version

  build_python3:
    dir: python
    env:
      image_version: 1.0.0
      repo_url: pm-srv.lan:3000/padremortius
      image_name: altlinux-p10
    cmds:
      - podman buildx build --build-arg VER=$image_version --build-arg REPO_URL=$repo_url -f Dockerfile -t $repo_url/$image_name-python:3-$image_version
      - podman push $repo_url/$image_name-python:3-$image_version
